### ISSUE TITLE
Case study speculation

### ISSUE THREAD

**Issue by Ranae** [hadley/mastering-shiny#236]
This book is already so much more helpful than any of the documentation I've read on Shiny. Thank you. 

In the ER case study, women have more stair related injuries than men. I am TOTALLY speculating here, but I think it is because women use stairs in the home more often than men due to taking on more of the housework. If a man's bedroom and family area are on the main floor, he seldom has any reason to use stairs, decreasing his chance of injury. If the washer/dryer, storage, and freezer are in the basement and the kids' rooms are on the second level, the main caretaker is up and down all day. 

Who would wear heels in their own house? :laughing: You might get some blowback there. 

Obviously I'm reading critically and I will let you know if I see anything a little more important. I already have like 6 apps out there and this is the first time I understand what's actually going on. Am trying to level up, so I'm glad I found this.

**Comment by hadley** [comment]
Hmmm, interesting hypothesis! If we split the plot up by home vs other:

![image](https://user-images.githubusercontent.com/4196/86602355-2bc42400-bf68-11ea-80f1-2664042c06f4.png)

The difference is definitely less pronounced, but I'm somewhat sceptical of this because after home, the next most common location is unknown:

```
  location                         n percent
  <chr>                        <dbl> <chr>  
1 Home                       647127. 53.765%
2 Unknown                    458802. 38.119%
3 Other Public Property       57625. 4.788% 
4 School                      25146. 2.089% 
5 Sports Or Recreation Place  11833. 0.983% 
6 Street Or Highway            2148. 0.178% 
7 Mobile Home                   783. 0.065% 
8 Farm                          150. 0.012% 
```

But presumably people would know if they're at home or not, so "other" might plausibly represent most cases outside of the home (and the categories seem to omit a lot of common places).

I did look through a bunch of randomly selected narratives, and didn't see any mention of high-heeled shoes; so I don't think there's much evidence to support my hypothesis.

---

It's interesting to contrast our two hypotheses at a high level:

* I suggest that women have a higher rate of injuries on stairs
* You suggest that women use the stairs more often

I don't think this dataset has the ability to distinguish between these two cases 😞 

Let me tweak my comment in the book to reflect that.
